version: "2.2"
services:

  php:
    build:
      context: .
    environment:
      - PHP_SESSION_HANDLER=redis
      - PHP_SESSION_PATH=tcp://redis:6379
    volumes:
      - ./:/var/www/html
      - ./docker/php/config/sessions.ini:/usr/local/etc/php/conf.d/sessions.ini
      - ./docker/php/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini
      - ./docker/php/config/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./docker/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - traefik
      - internal
    user: php
    entrypoint: php-fpm --nodaemonize
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginxinc/nginx-unprivileged:1.18.0
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
    labels:
      - traefik.http.routers.nginx.rule=Host(`horloge-nl.test`, `www.horloge-nl.test`)
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx-secure.rule=Host(`horloge-nl.test`, `www.horloge-nl.test`)
      - traefik.http.routers.nginx-secure.entrypoints=websecure
      - traefik.http.routers.nginx-secure.tls=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    networks:
      - traefik
      - internal

  meilisearch:
    image: getmeili/meilisearch:latest
    networks:
      - internal
    volumes:
      - meili-data:/data.ms

  traefik:
    image: traefik:v2.10.7
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/certs
      - --providers.file.watch=true
    ports:
      - "80:80"  # HTTP
      - "8080:8080"  # Traefik Dashboard
      - "443:443"  # HTTPS
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web  # Make sure this matches the defined entrypoint
      - traefik.http.routers.traefik-secure.service=api@internal
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.tls=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs  # Mount the directory containing your certificates
    networks:
      - traefik

volumes:
  mysql-data:
  meili-data:

networks:
  traefik:
    external: true
  internal:
    external: false